1:
 id: "1"
 answer: "You will purchase DIVX now, using Ether sent to our “smart contract” that lives on the Ethereum blockchain. This is an “exchange token.” Your wallet will have DIVX in it and you’ll hold onto those until the Divi blockchain is launched (in early Q2 2018). At that time, you’ll download the Divi wallet software and install it on your computer. We’ll have another smart contract that you’ll send the DIVX to it. We’ll send an equal amount of DIVI to your new wallet. After a 60 day window in which people can exchange their DIVX for DIVI, we’ll send everyone’s DIVX back to them."
 words:
  - DIVX
  - DIVI
  - difference
2:
 id: "2"
 answer: "After the token sale concludes we will work to register DIVX with several smaller exchanges such as Liqui.io, Etherdelta, and Changely. Because DIVX is an exchange token that will be burned, the larger exchanges won’t bother to list it.\nWhen the mainnet is ready, DIVI will be listed too as quickly as possible, and as our trade volume grows, we will get listed in bigger and better exchanges"
 words:
  - trade
  - exchange
  - DIVX
3:
 id: "3"
 answer: "What will happen with DIVX afterwards?"
 words:
  - after
  - later
  - DIVX
  - token
  - sale
  - ICO
4:
 id: "4"
 answer: "We originally took it from the word Divvy, which means “Divide up and Share.” It can also be an acronym for Decentralized Intuitive Value Initiative."
 words:
  - Divi
  - name
  - mean
  - meaning
5:
 id: "5"
 answer: "A masternode is a program that’s on your computer, or on a cloud server you rent, that connects with other masternodes. It communicates continually with them and keeps a full copy of the Divi blockchain, constantly checking that it’s correct, and adding new blocks. By putting your coins into a masternode, you get rewarded with more newly created coins for helping to run the network."
 words:
  - masternode
  - masternodes
  - What
  - explain
6:
 id: "6"
 answer: "Divi is the first to offer a 5 Tiered Masternode system. The levels of ownership are:\n1000 Coins — Level 1: Copper\n3000 Coins — Level 2: Silver +5%\n10,000 Coins — Level 3: Gold +10%\n30,000 Coins — Level 4: Platinum +15%\n100,000 Coins — Level 5: Diamond + 20%"
 words:
  - masternode
  - Tiered
  - tier 
  - required
7:
 id: "8"
 answer: "A silver masternode requires the same number of coins as 3 coppers. But the chance to win a block award it 5% better. However, 3 copper masternodes gives you 3 chances to win the lottery blocks, compared with only one for silver. But you’ll need 3 IP addresses. So there are pros and cons to each."
 words:
  - silver
  - copper
  - better
  - comparison
  - masternode  
8:
 id: "8"
 answer: "The Proof of Work “consensus” algorithm requires people to search for the answer to a complex mathematical puzzle, and it takes massive amounts of calculations (and electricity) to do it. Whoever finds the answer first gets to write the transactions into the next block, and they get coins as their reward for doing that. That’s bitcoin’s method. Proof of Stake just requires you to prove you have a certain amount of coins. So they sit in a wallet (or in our case they can be in multiple wallets for better security) and not much electricity needs to be used other than a bit to communicate with the network from your computer."
 words:
  - stake
  - proof
  - work
  - pow
  - pos
  - algorithm
9:
 id: "9"
 answer: "Although the protocol is currently under development and in pre-alpha state… we try not to speculate on the exact dates too much, as development can be pretty unpredictable. That being said, our roadmap is on track for an early Q1 2018 pre-alpha test."
 words:
  - ready
  - when
  - alpha
 10:
 id: "10"
 answer: "We are capping the crowdsale at 100,000 ETH and the only tokens in existence will be the ones created in the sale. Due to the varying exchange rates of DIVX to ETH it’s hard to predict what the “cap” would be. We estimate around 60–80 million."
 words:
  - limited
  - supply
  - tokens
  - max
  - cap
  - Tokensale
11:
 id: "3"
 answer: "Public Sale Phase 1: 30% Bonus. 1 ETH = 650 DIVX\nPublic Sale Phase 2: 15% Bonus. 1 ETH = 575 DIVX\nPublic Sale Final Phase: No Bonus. 1 ETH = 500 DIVX"
 words:
  - rates
  - ICO
  - Tokensale
  - price
12:
 id: "3"
 answer: "In fact, we have gotten 3 separate contract audits to ensure the validity and security of the code. Details can be found here: https://goo.gl/HrQ36D"
 words:
  - smart
  - contract
  - audit
  - audited

