name: "Divi"
info: " Click here to watch our video https://www.youtube.com/embed/zfOEU7pvSoM?autoplay=1 \n For more information visit https://diviproject.org/."
contract: "0x13f11C9905A08ca76e3e853bE63D4f0944326C72"
start: "4438800"
round1_start: ""
round1_rate: ""
round2_start: ""
round2_rate: ""
round3_start: ""
round3_rate: ""
end: ""
